- examples/android-client/app/build.gradle
- examples/android-client/app/src/main/AndroidManifest.xml
- examples/java-client/build.gradle
- sdk/build.gradle
android-client:
- Added INTERNET permission to AndroidManifest
- compile to implementation build.gradle
java-client:
- compile to implementation build.gradle
sdk:
- Added protobuf to gradle
- compile to api
- testCompile to testImplementation
> Configuration fixes

- examples/java-client/src/main/java/io/dronecore/example/DroneCoreExample.java
- sdk/dronecode-sdk/src/test/java/org/dronecode/sdk/DroneCoreTest.java
- sdk/templates/call.j2
- sdk/templates/request.j2
@RyanHurst: FYI
This PRs adds support for arguments, enabling e.g. setting RTL altitude or uploading a mission.
> Support arguments

- examples/java-client/README.md
- examples/java-client/build.gradle
- examples/java-client/gradle/wrapper/gradle-wrapper.properties
- examples/java-client/settings.gradle
- examples/java-client/src/main/java/io/dronecore/example/RunMission.java
- examples/java-client/src/main/java/io/dronecore/example/SetRtlAltitude.java
- examples/java-client/src/main/java/io/dronecore/example/TakeoffAndLand.java
- sdk/build.gradle
@RyanHurst: FYI
This adds a example running a simple mission.
Run it with `./gradlew runMission` from `examples/java-client`
> Add examples

- README.md
- examples/android-client/app/build.gradle
- examples/android-client/app/src/androidTest/java/io/mavsdk/androidclient/ExampleInstrumentedTest.java
- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java
- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsViewModel.java
- examples/android-client/app/src/test/java/io/mavsdk/androidclient/ExampleUnitTest.java
- examples/java-client/build.gradle
- examples/java-client/src/main/java/io/mavsdk/example/RunMission.java
- examples/java-client/src/main/java/io/mavsdk/example/SetRtlAltitude.java
- examples/java-client/src/main/java/io/mavsdk/example/TakeoffAndLand.java
- sdk/build.gradle
- sdk/dronecode-sdk/settings.gradle
- sdk/mavsdk/settings.gradle
- sdk/mavsdk/src/test/java/io/mavsdk/MavsdkTest.java
- sdk/settings.gradle
- sdk/templates/file.j2
- sdk/templates/struct.j2
It works for the java example and sdk tests. I haven't tested Android yet.
@RyanHurst: I would be glad if you could review that and try to build it for Android :blush:.
> rename to mavsdk

- examples/android-client/app/src/main/AndroidManifest.xml
- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java
- examples/android-client/app/src/main/res/values/strings.xml
- examples/android-client/build.gradle
- examples/android-client/gradle/wrapper/gradle-wrapper.properties
- sdk/README.md
- sdk/gradle/wrapper/gradle-wrapper.properties
updated gradle, fixed dronecode refrences
> Android dronecode removal

- README.md
@JonasVautherin Feels wrong to not link to your guide, since it is the only one. If you agree, you're free to move it elsewhere than this - e.g. as a Note in the quickstart?
Also, shouldnt this readme be linked from the sidebar of https://mavsdk.mavlink.io/develop/en/ ?
> README - add links to Jonas article.

- README.md
REAME updated to include Android Studio Emulator note.
> README update, Android Studio Emulator

- mavsdk_server/build.gradle
- sdk/build.gradle
> Bump mavsdk_server to 0.5.0, using binary v0.34.0

- sdk/build.gradle
MavenCentral fails to publish 0.5.0 for some reason
> Bump to 0.5.1

- examples/android-client/app/build.gradle
- examples/java-client/build.gradle
> Update mavsdk dependencies in examples (0.5.x)

- sdk/mavsdk/src/main/java/io/mavsdk/System.java
Related to https://github.com/mavlink/MAVSDK-Java/issues/36.
> Update proto submodule and add remaining plugins to System helper

- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java
[distinct()](https://rxmarbles.com/#distinct) will only get a new flight mode once. It should use [distinctUntilChanged()](https://rxmarbles.com/#distinctUntilChanged) instead
> Fix arm and flight mode subscribing in android example

- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java
> Clear disposables after dispose all in android example

- examples/java-client/build.gradle
- examples/java-client/src/main/java/io/mavsdk/example/SystemShell.java
@JonasVautherin 
Added a java-client example of the system shell plugin.
> Add system shell example

- examples/java-client/build.gradle
- examples/java-client/src/main/java/io/mavsdk/example/Calibrate.java
@jeremyyano: FYI
This adds an example for the `Calibration` plugin (actually trying to reproduce #37). It seems like it never calls `onComplete`, though.
> Add calibration example

- sdk/templates/stream.j2
Resolves #72 
@JonasVautherin, the code is building, but I don't know why I am not able to use the generated jar file to test the code properly. It's giving me several dependency issues. Though I am able to use the maven dependency (but it has the old code)
> Removed last object replay behaviour of streams

- README.md
- mavsdk_server/build.gradle
- mavsdk_server/src/main/cpp/native-lib.cpp
- mavsdk_server/src/main/java/io/mavsdk/mavsdkserver/MavsdkServer.java
- mavsdk_server/src/main/jniLibs/include/mavsdk_server_api.h
- sdk/README.md
- sdk/build.gradle
@divyanshu1234: Would you mind trying with those changes? If it works I'll push a new artifact 0.11.0 :+1:.
Resolves #71.
> Update to mavsdk_server v0.48.0

- README.md
- mavsdk_server/build.gradle
- sdk/README.md
- sdk/build.gradle
> Bump to 1.1.0 with mavsdk_server 1.2.0

- README.md
This adds some instructions for next time when I need to debug something in the library without having to push to maven.
> README: instructions how to bypass maven

- mavsdk_server/src/main/cpp/native-lib.cpp
- mavsdk_server/src/main/java/io/mavsdk/mavsdkserver/MavsdkServer.java
> mavsdk_server: expose destroy interface

- README.md
- mavsdk_server/build.gradle
- sdk/build.gradle
Should resolve https://github.com/mavlink/MAVSDK-Java/issues/123
> Bump mavsdk_server to 1.4.11

- README.md
> Remove obsolete link to blog post

- README.md
- mavsdk_server/build.gradle
- sdk/README.md
- sdk/build.gradle
- sdk/mavsdk/src/main/java/io/mavsdk/System.java
@Sefibrah: FYI
Related to https://github.com/mavlink/MAVSDK-Java/pull/167
> Prepare release 2.1.0

- examples/android-client/app/build.gradle
- examples/android-client/app/src/main/AndroidManifest.xml
- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java
- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsViewModel.java
- examples/android-client/build.gradle
- examples/android-client/gradle/wrapper/gradle-wrapper.properties
Bring the Android Client app a bit more up to date
> Update to 2.1.0, Java 17, gradle 8.6 / plugin 8.4.1

- README.md
This expands the docs on how to debug by copying in .so files.
This should save me an hour or two next time.
> Readme: how to avoid having .so overwritten

- mavsdk_server/src/main/cpp/native-lib.cpp
- mavsdk_server/src/main/java/io/mavsdk/mavsdkserver/MavsdkServer.java
Adds method that allows setting custom Mavlink IDs
> Fixes #179 Add method to run mavsdk server with custom IDs

- README.md
- mavsdk_server/build.gradle
This fixes https://github.com/mavlink/MAVSDK/issues/2477
> Update mavsdk-server to 2.14.1

- examples/android-client/app/build.gradle
- examples/android-client/app/src/main/AndroidManifest.xml
- examples/android-client/app/src/main/java/io/mavsdk/androidclient/MapsActivity.java
- examples/android-client/app/src/main/res/layout/activity_maps.xml
- examples/android-client/app/src/main/res/values/colors.xml
- examples/android-client/app/src/main/res/values/strings.xml
- examples/android-client/app/src/main/res/values/styles.xml
- examples/android-client/build.gradle
- examples/android-client/gradle.properties
- examples/android-client/gradle/wrapper/gradle-wrapper.properties
- mavsdk_server/build.gradle
- mavsdk_server/gradle/wrapper/gradle-wrapper.properties
- mavsdk_server/src/main/cpp/native-lib.cpp
- sdk/build.gradle
- sdk/gradle/wrapper/gradle-wrapper.properties
- sdk/templates/request.j2
As discussed in https://github.com/mavlink/MAVSDK-Proto/issues/376
Also needed to fix native-lib.cpp because of https://github.com/mavlink/MAVSDK/commit/0268ed5910a27a11dc4a5da2acee7b09b6615131
> Update mavsdk-server to 3.5.0

- .github/workflows/main.yml
Making sure I am not the bottleneck when publishing to Maven Central :innocent:.
> Add CI to deploy artifacts to Maven Central
